imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app_locales: en|sv|ro
    theme: flatly
    theme_css: "bootstrap.min.css"
    themes_root: "bundles/vendor/bower-asset/bootswatch"
    themes_search_pattern: "%kernel.root_dir%/../web/%themes_root%/*/%theme_css%"
    recs_per_page: 10
    first_page: 1

framework:
    #esi:             ~
    translator:      { fallbacks: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    ide: eclipse
    form:
      csrf_protection: false

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:  "app.exception_controller:showAction"
    paths: 
      "%kernel.root_dir%/../src/AppBundle/Resources/views": twig_templates

# Doctrine Configuration
doctrine:
    dbal:
      connections:
        mynix:
          driver:   "%database_driver%"
          host:     "%database_host%"
          port:     "%database_port%"
          dbname:   "%database_name%"
          user:     "%database_user%"
          password: "%database_password%"
          charset:  UTF8
          mapping_types:
             bit: boolean
          # if using pdo_sqlite as your database driver:
          #   1. add the path in parameters.yml
          #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
          #   2. Uncomment database_path in parameters.yml.dist
          #   3. Uncomment next line:
          #     path:     "%database_path%"
                    
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

assetic:  
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: /usr/bin/node
    filters:
        cssrewrite: ~
        uglifyjs2: 
          bin: /usr/bin/uglifyjs
        uglifycss:
          bin: /usr/bin/uglifycss
        jpegoptim:
          bin: /usr/bin/jpegoptim
          apply_to: '\.jp?g$'
        optipng:
          bin: /usr/bin/optipng
          apply_to: '\.png$'
          level: 3
    twig:
      functions:
        jpegoptim: ~
    assets:
      app_css:
        inputs:
          - %kernel.root_dir%/../web/bundles/app/css/my-style.css
      bootstrap_js:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/bootstrap/dist/js/bootstrap.min.js
      jquery:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/jquery/jquery.min.js
      fa_css:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/css/font-awesome.min.css
      fa_eot:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/fontawesome-webfont.eot
        output:
          "fonts/fontawesome-webfont.eot"
      fa_svg:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/fontawesome-webfont.svg
        output:
          "fonts/fontawesome-webfont.svg"
      fa_ttf:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/fontawesome-webfont.ttf
        output:
          "fonts/fontawesome-webfont.ttf"
      fa_woff:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/fontawesome-webfont.woff
        output:
          "fonts/fontawesome-webfont.woff"
      fa_woff2:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/fontawesome-webfont.woff2
        output:
          "fonts/fontawesome-webfont.woff2"
      fa_otf:
        inputs:
          - %kernel.root_dir%/../web/bundles/vendor/bower-asset/font-awesome/fonts/FontAwesome.otf
        output:
          "fonts/fontawesome-webfont.otf"
          
monolog:
    handlers:
        applog:
            type: stream
            path: '%kernel.root_dir%/../var/logs/symfony.log'
            level: error
        main:
            type: fingers_crossed
            action_level: warning
            handler: file
        file:
            type: stream
            level: debug
        syslog:
            type: syslog
            level: error