app:
  resource: '@AppBundle/Controller/'
  type: annotation
  prefix: /{_locale}/{_theme}/
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
homepage:
  path: /{_locale}/{_theme}
  requirements:
    _locale: '%app_locales%'
  defaults:
    _controller: AppBundle:EntityList:browseEntities
    _locale: '%locale%'
    _theme: '%theme%'
    page: '%first_page%'
    limit: '%recs_per_page%'
entities_list:
  path: /{_locale}/{_theme}/entities/browse/{page}/{limit}
  requirements:
    _locale: '%app_locales%'
    page: '[1-9]\d*'
    limit: '[1-9]\d*'
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: AppBundle:EntityList:browseEntities
    page: '%first_page%'
    limit: '%recs_per_page%'
browse_entity:
  path: /{_locale}/{_theme}/entity/browse/{entity}/{page}/{limit}
  requirements:
    _locale: '%app_locales%'
    page: '[1-9]\d*'
    limit: '[1-9]\d*'
    entity: ([a-zA-Z][\w\d$_]*)?
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: AppBundle:EntityBrowse:browseEntity
    page: '%first_page%'
    limit: '%recs_per_page%'
view_entity:
  path: /{_locale}/{_theme}/entity/view/{entity}/{id}
  requirements:
    _locale: '%app_locales%'
    entity: '[a-zA-Z][\w\d$_]*'
    id: \d+
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: AppBundle:EntityView:viewEntity
    id: 0
  methods:
  - GET
edit_entity:
  path: /{_locale}/{_theme}/entity/edit/{entity}/{id}/{success}
  requirements:
    _locale: '%app_locales%'
    entity: '[a-zA-Z][\w\d$_]*'
    id: \d+
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: AppBundle:EntityEdit:editEntity
    success: null
    id: -1
  methods:
  - POST
  - GET
delete_entity:
  path: /{_locale}/{_theme}/entity/delete/{entity}/{id}
  requirements:
    _locale: '%app_locales%'
    entity: '[a-zA-Z][\w\d$_]*'
    id: \d+
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: AppBundle:Generic:deleteEntity
  methods:
  - GET
help:
  path: /{_locale}/{_theme}/help
  requirements:
    _locale: '%app_locales%'
  defaults:
    _locale: '%locale%'
    _theme: '%theme%'
    _controller: FrameworkBundle:Template:template
    template: '@twig_templates/help.html.twig'
pageNotFound:
  path: /{path}
  defaults:
    _controller: AppBundle:PageNotFound:pageNotFound
    path: ''
  requirements:
    path: .*
bootswatch_css:
  path: '%kernel.root_dir%/../web/vendor/bower-asset/bootswatch/'    