parameters: null
services:
  app.entity_voter:
    class: AppBundle\Security\EntityVoter
    tags:
    - name: security.voter
    public: false
  app.twig.app_extension:
    public: false
    class: AppBundle\Twig\AppExtension
    arguments:
    - '%app_locales%'
    tags:
    - name: twig.extension
  app.twig.intl_extension:
    public: false
    class: Twig_Extensions_Extension_Intl
    tags:
    - name: twig.extension
  app.redirect_to_preferred_locale_listener:
    class: AppBundle\EventListener\RedirectToPreferredLocaleListener
    arguments:
    - '@router'
    - '%app_locales%'
    - '%locale%'
    tags:
    - name: kernel.event_listener
      event: kernel.request
      method: onKernelRequest
  validator.foreign_key_validator:
    class: AppBundle\Validator\Constraints\ForeignKeyValidator
    arguments:
    - '@doctrine'
    tags:
    - name: validator.constraint_validator