parameters: null
services:
  app.entity_voter:
    class: Mynix\DemoBundle\Security\EntityVoter
    tags:
    - name: security.voter
    public: false
    arguments:
    - '@twig'
    - '%kernel.debug%'
  app.twig.app_extension:
    public: false
    class: Mynix\DemoBundle\Twig\AppExtension
    arguments:
    - '%app_locales%'
    - '%themes_search_pattern%'
    - '%themes_root%'
    - '%theme_css%'
    - '%default_theme%'
    - '@request_stack'
    tags:
    - name: twig.extension
  app.twig.intl_extension:
    public: false
    class: Twig_Extensions_Extension_Intl
    tags:
    - name: twig.extension
  app.redirect_to_preferred_locale_listener:
    class: Mynix\DemoBundle\EventListener\RedirectToPreferredLocaleListener
    arguments:
    - '@router'
    - '%app_locales%'
    - '%locale%'
    - '%default_theme%'
    tags:
    - name: kernel.event_listener
      event: kernel.request
      method: onKernelRequest
  app.exception_controller:
    class: Mynix\DemoBundle\Controller\ExceptionController
    arguments:
    - '@twig'
    - '%kernel.debug%'
  validator.foreign_key_validator:
    class: Mynix\DemoBundle\Validator\Constraints\ForeignKeyValidator
    arguments:
    - '@doctrine'
    tags:
    - name: validator.constraint_validator
  lang.autodetect:
    class: Mynix\DemoBundle\Services\LanguageDetector
    arguments:
    - '%kernel.default_locale%'
    - '%app_locales%'
    - '@request_stack'